// @jasonyu0100
// Offline, demand-led voice-line generation: cast sheet + authored text → pinned voice assets.
// Usage: npm run voices -- <experienceId|story-slug|all> [--dry-run]
// Each line is keyed by its input digest; unchanged lines are reused, changed lines regenerate.
import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { basename, join, resolve } from 'node:path';
import type { VoiceCast, VoiceLine, VoiceLineAsset } from '../src/core/voice-cast';
import { planVoiceLines } from '../src/core/voice-cast';
import { replicateInputDigest, runReplicatePrediction, selectReplicateOutputUrl } from '../src/provider/replicate';
import { experiences } from '../src/story';
import { casts } from '../src/story/casting';
import { productionFor } from '../src/story/productions';
import { loadLocalEnvironment, requireSetting } from './config';
import { fileDigest } from './lib/acquisition-kit';

const MODEL = 'minimax/speech-02-turbo';

type LineReceipt = { inputDigest: string; sha256: string; predictionId: string; text: string; voiceId: string };
type VoiceReceipt = { model: string; lines: Record<string, LineReceipt> };

const projectRoot = resolve(import.meta.dirname, '..');
const args = process.argv.slice(2);
const dryRun = args.includes('--dry-run');
const target = args.find((argument) => !argument.startsWith('--')) ?? 'all';

function synthesisInput(line: VoiceLine): Record<string, unknown> {
  return {
    text: line.text,
    voice_id: line.profile.voiceId,
    speed: line.profile.speed,
    pitch: line.profile.pitch,
    emotion: line.profile.emotion,
    audio_format: 'mp3',
    bitrate: 128000,
    sample_rate: 32000,
    channel: 'mono',
    language_boost: 'English',
    english_normalization: true,
  };
}

const sleep = (ms: number): Promise<void> => new Promise((done) => setTimeout(done, ms));

async function synthesize(token: string, line: VoiceLine, evidenceDirectory: string): Promise<{ id: string; url: string }> {
  const input = synthesisInput(line);
  for (let attempt = 1; ; attempt += 1) {
    try {
      const prediction = await runReplicatePrediction({ token, model: MODEL, input, evidenceDirectory, evidenceName: line.assetId });
      return { id: prediction.id, url: selectReplicateOutputUrl(prediction.output) };
    } catch (error) {
      const throttled = String(error).includes('HTTP 429');
      if (!throttled || attempt >= 6) throw error;
      await sleep(4000 * attempt);
    }
  }
}

function moduleName(storyFile: string): string {
  return basename(storyFile, '.ts');
}

function camel(slug: string): string {
  return slug.replace(/-([a-z])/g, (_match, letter: string) => letter.toUpperCase());
}

function renderModule(slug: string, lines: VoiceLineAsset[]): string {
  const rows = lines.map((line) => {
    const variant = line.variantIndex === undefined ? '' : `, variantIndex: ${line.variantIndex}`;
    return `  { assetId: '${line.assetId}', momentId: '${line.momentId}'${variant}, sourcePath: '${line.sourcePath}', sha256: '${line.sha256}' },`;
  });
  return [
    '// @jasonyu0100',
    `// Generated by scripts/generate-voices.ts from src/story/casting/${slug}.ts. Do not edit; rerun \`npm run voices -- ${slug}\`.`,
    "import type { VoiceLineAsset } from '../../core/voice-cast';",
    '',
    `export const ${camel(slug)}VoiceLines: readonly VoiceLineAsset[] = [`,
    ...rows,
    '];',
    '',
  ].join('\n');
}

async function generateFor(experienceId: string, cast: VoiceCast, token: string | undefined): Promise<void> {
  const experience = experiences.find((candidate) => candidate.id === experienceId);
  if (!experience) throw new Error(`Unknown experience ${experienceId}`);
  const production = productionFor(experienceId);
  const slug = moduleName(production.storyFile);
  const assetRoot = `assets/generated/${production.productionId}/voice`;
  const evidenceDirectory = join(projectRoot, 'productions', production.productionId, 'evidence', 'voices');
  const receiptPath = join(projectRoot, 'productions', production.productionId, 'evidence', 'voices.receipt.json');
  await mkdir(join(projectRoot, assetRoot), { recursive: true });
  await mkdir(evidenceDirectory, { recursive: true });

  const receipt: VoiceReceipt = existsSync(receiptPath) ? JSON.parse(await readFile(receiptPath, 'utf8')) as VoiceReceipt : { model: MODEL, lines: {} };
  const lines = planVoiceLines(experience, cast);
  const pinned: VoiceLineAsset[] = [];
  let reused = 0;
  let generated = 0;

  for (const line of lines) {
    const sourcePath = `${assetRoot}/${line.assetId}.mp3`;
    const target = join(projectRoot, sourcePath);
    const inputDigest = replicateInputDigest(synthesisInput(line));
    const retained = receipt.lines[line.assetId];
    if (retained && retained.inputDigest === inputDigest && existsSync(target) && (await fileDigest(target)) === retained.sha256) {
      pinned.push({ assetId: line.assetId, momentId: line.momentId, ...(line.variantIndex === undefined ? {} : { variantIndex: line.variantIndex }), sourcePath, sha256: retained.sha256 });
      reused += 1;
      continue;
    }
    if (dryRun) {
      console.log(`  would generate ${line.assetId} [${line.profile.voiceId} ×${line.profile.speed} ${line.profile.pitch >= 0 ? '+' : ''}${line.profile.pitch} ${line.profile.emotion}] "${line.text.slice(0, 60)}"`);
      continue;
    }
    if (!token) throw new Error('REPLICATE_API_TOKEN is required to generate voice lines');
    const { id, url } = await synthesize(token, line, evidenceDirectory);
    const response = await fetch(url);
    if (!response.ok) throw new Error(`Download failed for ${line.assetId}: HTTP ${response.status}`);
    await writeFile(target, Buffer.from(await response.arrayBuffer()));
    const sha256 = await fileDigest(target);
    receipt.lines[line.assetId] = { inputDigest, sha256, predictionId: id, text: line.text, voiceId: line.profile.voiceId };
    pinned.push({ assetId: line.assetId, momentId: line.momentId, ...(line.variantIndex === undefined ? {} : { variantIndex: line.variantIndex }), sourcePath, sha256 });
    generated += 1;
    console.log(`  ${line.assetId} ← ${line.profile.voiceId} (${id})`);
    await sleep(1200);
  }

  if (dryRun) {
    console.log(`${experienceId}: ${reused} pinned, ${lines.length - reused} pending`);
    return;
  }
  for (const staleId of Object.keys(receipt.lines)) {
    if (!lines.some((line) => line.assetId === staleId)) delete receipt.lines[staleId];
  }
  await writeFile(receiptPath, `${JSON.stringify(receipt, null, 2)}\n`);
  await writeFile(join(projectRoot, 'src/story/generated', `${slug}.voices.ts`), renderModule(slug, pinned));
  console.log(`${experienceId}: ${generated} generated, ${reused} reused → src/story/generated/${slug}.voices.ts`);
}

await loadLocalEnvironment(projectRoot);
const token = dryRun ? process.env.REPLICATE_API_TOKEN : requireSetting('REPLICATE_API_TOKEN');
const selected = target === 'all'
  ? Object.keys(casts)
  : Object.keys(casts).filter((experienceId) => experienceId === target || moduleName(productionFor(experienceId).storyFile) === target);
if (selected.length === 0) throw new Error(`No voice cast matches ${target}`);
for (const experienceId of selected) {
  const cast = casts[experienceId];
  if (!cast) throw new Error(`No voice cast registered for ${experienceId} in src/story/casting/index.ts`);
  console.log(`${experienceId}`);
  await generateFor(experienceId, cast, token);
}
